### ISSUE TITLE
Rename Pillar

### ISSUE THREAD

**Issue by jcbwlkr** [ardanlabs/gotraining#242]
@ardan-bkennedy when I discuss decoupling and go through the whole Xenia -> Pillar exercise I find myself stumbling on the name "Pillar" because it sounds so similar to the interface "Puller". I think this also creates some "who's on first" kind of confusion for the students as well. Let's rename it.

**Comment by ardan-bkennedy** [comment]
I have wanted to move the system type before the Copy function because I think that is where it belongs in the conversation.

To address this issue. I am concerned because this is core material and it has been published outside this repo. The biggest place is the Ultimate Go video.

**Comment by jcbwlkr** [comment]
We decided to leave this as is for now.
