### ISSUE TITLE
[QUESTION] Why pass a global var as argument

### ISSUE THREAD

**Issue by barockok** [ardanlabs/gotraining#253]
https://github.com/ardanlabs/gotraining/blob/47261e94421eaad383d5c6bcfdb4e60087fa86f0/topics/go/concurrency/channels/example5/example5.go#L79

Hi @ardan-bkennedy,

why you pass the `complete` var into `processor` function when actually `complete` is a global variable that `processor` function can access it directly without passing it as an argument to it.

I'm currently joining your course **Ultimate Go Programming** on safaribooksonline,  and I don't know where is the right place to ask you a question so I land it here.

**Comment by ardan-bkennedy** [comment]
I should move those channels inside of the `main` function. This is a very old piece of code and sometimes when you try to keep something simple you do the wrong things. We don't want to use global variables in production code. Functions should always be precise and ask for the things they need is detail.

**Comment by jcbwlkr** [comment]
Thanks for the catch, @barockok! Fixed by @flyinprogrammer  in #256
