### ISSUE TITLE
[question]: Purpose of the file "topics/go/concurrency/patterns/advanced/logger/logger.go"

### ISSUE THREAD

**Issue by superstas** [ardanlabs/gotraining#273]
Hi there!

I want to ask about some inconsistency. There are two loggers in "patterns" section ( topics/go/concurrency/patterns ):
- [Logger](https://github.com/ardanlabs/gotraining/tree/master/topics/go/concurrency/patterns/logger)
- [Advanced logger](https://github.com/ardanlabs/gotraining/tree/master/topics/go/concurrency/patterns/advanced/logger)

The only difference between their main.go files is using custom/stdlib logger, but "advanced logger" has empty package logger (https://github.com/ardanlabs/gotraining/blob/master/topics/go/concurrency/patterns/advanced/logger/logger.go) - https://www.diffchecker.com/5vcK6nKY
It seems "advanced/logger" isn't used.

Is it a valid package?
Thank you!

**Comment by ardan-bkennedy** [comment]
I live code in class so that is why it looks empty. That is there by design.

**Comment by ardan-bkennedy** [comment]
@superstas . Here is an example
https://www.youtube.com/watch?v=zDCKZn4-dck

Also, can you send me an email please:  bill@ardanlabs.com
It's all good, I really appreciate the help. Just want to talk.
