### ISSUE TITLE
Funny unconscious impersonification of a rapper by William Kennedy

### ISSUE THREAD

**Issue by gdeverlant** [ardanlabs/gotraining#297]
Hi everyone I just had a blast watching the introduction video of William on this link:

http://www.informit.com/store/ultimate-go-programming-livelessons-9780134757483

I think that someone should make a remix of this video adding some dirty rap beat while William is talking about his course. This would become a major hit.

I can't stop laughing at this!

Have a nice day!

**Comment by whisper2chen** [comment]
a rapper ?

**Comment by gdeverlant** [comment]
Yeah he is moving like a rapper in a rap video clip but he ain't one! :D
