### ISSUE TITLE
reading: "Errors are handled in return values" links to google+

### ISSUE THREAD

**Issue by dvrkps** [ardanlabs/gotraining#302]

**Comment by ardan-bkennedy** [comment]
Can you please provide more details?

**Comment by dvrkps** [comment]
Sure, 
https://github.com/ardanlabs/gotraining/tree/master/reading
at Error handling... 
link to Russ Cox article "Errors are handled in return values" links to google+ url

**Comment by StephenBrown2** [comment]
Specifically this line: https://github.com/ardanlabs/gotraining/blame/master/reading/README.md#L137

**Comment by ardan-bkennedy** [comment]
I guess that post or response is lost. I will remove it. Do you have a better suggestion or have you found it?

**Comment by dvrkps** [comment]
Yes, remove it.
