### ISSUE TITLE
【about Nanosecond 】

### ISSUE THREAD

**Issue by dagang007** [ardanlabs/gotraining#305]
Hi , according to ur blog , i write a test :
`
startingTime := time.Now().UTC()
 time.Sleep( 1000 * time.Nanosecond )
 endingTime := time.Now().UTC()

var duration time.Duration = endingTime.Sub( startingTime )

fmt.Printf( "%d \n", duration.Microseconds() )
`

the result is 1000

**Comment by ardan-bkennedy** [comment]
Duration is based on an int64 and it represents nanoseconds.

You asked to sleep for 1 microsecond, so yes, you should exepect to see `1` displayed if there is no real latency between the call to `time.Sleep` and setting `endingTime`. You are calculating a wall clock and on your compute environment I can't predict scheduling.

I ran your code on the playground

https://play.golang.org/p/ybT80OdXjh1

It is giving the right result.

**Comment by dagang007** [comment]
> Duration is based on an int64 and it represents nanoseconds.
> 
I change code as ` time.Sleep( 1000 * time.Microsecond ) `  and Print duration.Milliseconds() , it gave the right result 1 . 

So i guess my environment ( win7 + go 1.13 ) may don't support Nanosecond

**Comment by ardan-bkennedy** [comment]
Download the 1.14 release candidate and try it again. If this still happens maybe you found a bug?

**Comment by ardan-bkennedy** [comment]
Download the 1.14 release candidate and try it again. If this still happens maybe you found a bug?

**Comment by dagang007** [comment]
Thanks a lot
