### ISSUE TITLE
slice.Min() and slice.Max() don't account for nil or empty slices

### ISSUE THREAD

**Issue by ayang64** [ardanlabs/gotraining#313]
maybe this complicates things but i think `slice.Max()` and `slice.Min()` should return an error.

there is no good way to return a value that is out of band (like -1 nor is there a `NaN` like with floats).

so the best way to signal an error like a `nil` or empty slice is via an error value.

the result is that if you pass a `nil` or empty slice, we immediately access an element in our slice that is out of bounds when we prime our `max` value.

also, i feel like the functions have a more general path -- instead having to check if the supplied slice has only 1 element, we can check if we're working on our first iteration in the inner loop by having range return the index.

**Comment by Jared-Prime** [comment]
:+1: was just about to open this

**Comment by ardan-bkennedy** [comment]
What piece of code is this attached to?

**Comment by ayang64** [comment]
I submitted a PR for `slices.Max()` above.  The same applies to `slices.Min()`.
