### ISSUE TITLE
[simulations] Use rand with non-fixed seed.

### ISSUE THREAD

**Issue by heikkilamarko** [ardanlabs/gotraining#341]
The simulations under `gotraining/topics/go/algorithms/simulations/` use `rand` with a fixed seed. Using a fixed seed will produce the same output on every run. 

A better way would be to use a non-fixed seed: 

```go
var r = rand.New(rand.NewSource(time.Now().UnixNano()))

day := r.Intn(daysInYear)
```

**Comment by ardan-bkennedy** [comment]
Agreed but in this case, having the same result for these examples are important. We plan to add tests and we need consistent results. Thanks for thinking about this.

**Comment by heikkilamarko** [comment]
I see. Thanks for the reply. Closing the issue...
