### ISSUE TITLE
Inner type promotion

### ISSUE THREAD

**Issue by myers-dev** [ardanlabs/gotraining#368]
Inner type promotion from the lecture 4.3 - Embedding , example https://go.dev/play/p/mbuA2SDiHKV?v=goprev
is not working as intended

 ./prog.go:43:4: ad.notify undefined (type admin has no field or method notify)

Go build failed.

**Comment by ardan-bkennedy** [comment]
Your playground example will not work since you are not embedding. The code examples in the training do appear to be correct. I just want to double check your version is not possibility a typo?

https://github.com/ardanlabs/gotraining/tree/master/topics/go/language/embedding
