### ISSUE TITLE
Compilation error in example

### ISSUE THREAD

**Issue by OStrekalovsky** [ardanlabs/gotraining#370]
go version: Go 1.19
compilation error: entity.ID undefined (type T has no field or method ID)

https://github.com/ardanlabs/gotraining/blob/b09413a050a09ea57a990db7452eb2193adaa5ac/topics/go/generics/07-field-access/generic.go#L89

**Comment by ardan-bkennedy** [comment]
I know about this. The original spec said this would work. They never got to it before the release. I am not sure when this will be available. This is functionality I am looking forward to.
