### ISSUE TITLE
Link to Pikes 5 rules is wrong

### ISSUE THREAD

**Issue by tebeka** [ardanlabs/gotraining#372]
The link to Pikes 5 rules in `reading/README.md` should be https://users.ece.utexas.edu/~adnan/pike.html

**Comment by russoj88** [comment]
Looks like it's actually 6 rules: https://twitter.com/rob_pike/status/998681790037442561

**Comment by ardan-bkennedy** [comment]
Would you like to provide a PR with this link?
http://doc.cat-v.org/bell_labs/pikestyle
