### ISSUE TITLE
Chapter composition for Go

### ISSUE THREAD

**Issue by ambili8** [ardanlabs/gotraining#381]

**Comment by ardan-bkennedy** [comment]
What is this issue for?

**Comment by ambili8** [comment]
Hi Bill,

I just added a task for myself in Github to write chapters for Go.

Thanks & Regards,
Ambili

**Comment by ardan-bkennedy** [comment]
I would not leave this here as a todo. Let's find another place for this.

**Comment by ambili8** [comment]
ok
