### ISSUE TITLE
slices.Clip description

### ISSUE THREAD

**Issue by pavelosipyants-sothebys2** [ardanlabs/gotraining#383]
In the post - https://www.ardanlabs.com/blog/2023/08/golang-slices-clip-clone-compact.html

Figure 3 shows that after `list = slices.Clip(list)` new `list` slice has a different underlying array with size 1.

But according to this code this is wrong:
```go
package main

import (
	"fmt"
)

func main() {
	var arr [10000]int
	fmt.Println("arr", &arr[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(arr), cap(arr))

	slArr := arr[:]
	fmt.Println("slArr", &slArr[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(slArr), cap(slArr))

	slArr = arr[:1:10]
	fmt.Println("slArr", &slArr[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(slArr), cap(slArr))

	sl := make([]int, 1, 10000)
	fmt.Println("sl", &sl[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(sl), cap(sl))

	sl = sl[:]
	fmt.Println("sl", &sl[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(sl), cap(sl))

	sl = sl[:1:10]
	fmt.Println("sl", &sl[0])
	fmt.Printf("Len(%d), Cap(%d)\n", len(sl), cap(sl))
}
```

Notice, address of `&slArr[0]` or `&sl[0]` doesn't change after changing the capacity.

Or did I understand smth wrong?

**Comment by ardan-bkennedy** [comment]
Your code example is not using the slices API at all?

Your 3 index slice examples are a smell. I have never found a reason for the last two values not to be the same.

**Comment by ardan-bkennedy** [comment]
Ok. I'll look at this again. It seems I did make the wrong conclusion. After review I'll fix anything that needs to be fixed. 

Thanks!!

**Comment by ardan-bkennedy** [comment]
OMG!  How did I miss that when I was reviewing this post :(

THANK YOU for finding this and creating an issue. Can you please send me an email. bill@ardanlabs.com.  I would like to give you access to the Go Bundle.

I should have a fix in the next hour.

**Comment by ardan-bkennedy** [comment]
I've been out for a few days but I don't see it. Can you send it again please.

**Comment by ardan-bkennedy** [comment]
What is your email?
