### ISSUE TITLE
A few differences on the interfaces's exercise

### ISSUE THREAD

**Issue by gabelula** [ardanlabs/gotraining#72]
The instructions in the comments of the template:

https://github.com/ardanlabs/gotraining/blob/master/topics/interfaces/exercises/template1/template1.go

are slightly different than in the exercise's instructions:

https://github.com/ardanlabs/gotraining/tree/master/topics/interfaces

**Comment by ardan-bkennedy** [comment]
Thanks for the issue. I updated the example and fixed the instructions.
