### ISSUE TITLE
Add Linux and BSD to the install list?

### ISSUE THREAD

**Issue by russel** [ardanlabs/gotraining#74]
The front page assumes attenders are using either Windows or OSX, I have been finding an increasing number of Ubuntu, and Linux generally, users on workshops. Often these people can trivially install using packaging. Sadly though sometimes this leads to using an old version of Go. I suspect similar situation ofr the BSD users. It would be good to give these people sensible installation instructions on a par with Windows and OSX users.

**Comment by ardan-bkennedy** [comment]
@russel I added some small comments but there really isn't any good post on the subject. I prefer people did not use apt-get for installing Go. Curious what you think?

**Comment by russel** [comment]
@ardan-bkennedy I use aptitude rather than apt-get on Debian, and dnf on Fedora. I see no problem in getting the Go core via package management, at least on Debian Sid and Fedora Rawhide – and I suspect the same will be true on Arch. I tend not to use the Debian or Fedora packages for non-core additions, just using the standard "go get" to fetch things into the current workspace. Using the Go distribution means using a generic Linux build which can cause problems with shared libraries – although the policy of Go is static build, there are some shared library dependencies. One could always compile from source, but using the platform packaging for the core seems to be a good compromise. Of course this may mean using a slightly older version for a while, but Debian Sid and Fedora Rawhide are never far behind the latest release. Obviously for people using ancient builds such as Debian Stable or Fedora 21, they are much better advised to use the standard Go distributions if they can.
